apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 443640361232.dkr.ecr.ap-northeast-2.amazonaws.com/demo-nestjs-backend
  newName: 443640361232.dkr.ecr.ap-northeast-2.amazonaws.com/demo-nestjs-backend
  newTag: 388e77cb
resources:
- ../../base
patchesStrategicMerge:
- nestjs-backend-deployment-patch.yaml
- nestjs-backend-service-patch.yaml
